version: '3'

services:

  app:
    container_name: Cushion-Server
    image: cushiondb/cushiondb-server:latest
    ports:
      - "3001:3001"
    networks:
      backend:
        aliases:
          - backend
    depends_on:
      - "db"
    env_file:
      - .env/.app_env.env
      - .env/.vapid_keys.env
      - .env/.couch_credentials.env
      - .env/.prod.env

  db:
    container_name: CouchDB
    image: cushiondb/cushiondb-couch:latest
    volumes:
      - data:/opt/couchdb/data
    ports:
      - "5984:5984"
    env_file:
      - .env/.couch_credentials.env
    networks:
      backend:
        aliases:
          - backend
          - database

networks: 
  backend:

volumes:
  data:
