version: '3'
services:
  app:
    image: cushion-server
    ports:
      - "3001:3001"
    links:
      - db
    env_file:
      - temp.env
    depends_on:
      - "db"
    # environment:
    #   - COUCHDB_USER=${COUCHDB_USER}
    #   - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
  db:
    image: cushion-couch
    volumes:
      - data:/opt/couchdb/data
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}

volumes:
  data:
