version: '3'

services:

  app:
    image: cushion-server:latest
    ports:
      - "3001:3001"
    networks:
      backend:
        aliases:
          - backend
    depends_on:
      - "db"
    env_file:
      - .env/.app_env.env
      - .env/.vapid_keys.env
      - .env/.couch_credentials.env
    environment:
      - NODE_ENV=production
      - COUCH_BASE_URL=http://backend:5984/

  db:
    image: cushion-couch:latest
    volumes:
      - data:/opt/couchdb/data
    ports:
      - "5984:5984"
    env_file:
      - .env/.couch_credentials.env
    networks:
      backend:
        aliases:
          - backend
          - database
    logging:
      driver: none

networks: 
  backend:

volumes:
  data:
